# Generated by Django 3.2.23 on 2023-12-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semaine',
        ),
    ]
