# Generated by Django 3.2.23 on 2023-12-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_semaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feu',
            name='rue',
        ),
        migrations.DeleteModel(
            name='Heure',
        ),
        migrations.DeleteModel(
            name='Jour',
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
        migrations.DeleteModel(
            name='Feu',
        ),
        migrations.DeleteModel(
            name='Rue',
        ),
    ]
