# Generated by Django 3.2.23 on 2023-12-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_auto_20231216_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feu',
            fields=[
                ('idFeu', models.AutoField(primary_key=True, serialize=False, verbose_name='id du feu')),
                ('etatFeu', models.CharField(default='rouge', max_length=50, verbose_name='état (actuel) du feu')),
            ],
        ),
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('idRue', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la rue')),
                ('nomRue', models.CharField(max_length=50, verbose_name='nom de la rue')),
                ('feu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feu')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('idVehicule', models.AutoField(primary_key=True, serialize=False, verbose_name='id du véhicule')),
                ('typeVehicule', models.CharField(max_length=50, verbose_name='type de véhicule')),
            ],
        ),
        migrations.CreateModel(
            name='Temps',
            fields=[
                ('idTemps', models.AutoField(primary_key=True, serialize=False, verbose_name='id du temps')),
                ('dateHeure', models.DateTimeField(verbose_name='date de la détection')),
                ('semaine', models.IntegerField(verbose_name='semaine de la détection')),
                ('jourSemaine', models.CharField(max_length=50, verbose_name='jour de la détection')),
                ('isWeekEnd', models.BooleanField(verbose_name='indicateur de week-end')),
                ('feu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feu')),
                ('rue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rue')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='rue',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicule'),
        ),
    ]
