# Generated by Django 5.0 on 2024-01-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_detection_etatfeu_feu_rue_temps_typevehicule_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='feu',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='rue',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='temps',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='vehicule',
        ),
        migrations.RemoveField(
            model_name='etatfeu',
            name='feu',
        ),
        migrations.RemoveField(
            model_name='rue',
            name='feu',
        ),
        migrations.RemoveField(
            model_name='typevehicule',
            name='vehicule',
        ),
        migrations.DeleteModel(
            name='Temps',
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='etatFeu',
        ),
        migrations.DeleteModel(
            name='Feu',
        ),
        migrations.DeleteModel(
            name='Rue',
        ),
        migrations.DeleteModel(
            name='TypeVehicule',
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
    ]
