# Generated by Django 5.0 on 2024-01-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='feu',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='rue',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='temps',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='vehicule',
        ),
        migrations.RemoveField(
            model_name='feu',
            name='etatFeu',
        ),
        migrations.RemoveField(
            model_name='feu',
            name='rue',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='typevehicule',
        ),
        migrations.DeleteModel(
            name='Temps',
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='etatFeu',
        ),
        migrations.DeleteModel(
            name='Feu',
        ),
        migrations.DeleteModel(
            name='Rue',
        ),
        migrations.DeleteModel(
            name='TypeVehicule',
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
    ]
