# Generated by Django 5.0 on 2024-01-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0021_remove_detection_feu_remove_detection_rue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatFeu',
            fields=[
                ('idEtatFeu', models.AutoField(primary_key=True, serialize=False)),
                ('nomEtatFeu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('idRue', models.AutoField(primary_key=True, serialize=False)),
                ('nomRue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temps',
            fields=[
                ('idTemps', models.AutoField(primary_key=True, serialize=False)),
                ('dateHeure', models.DateTimeField()),
                ('semaine', models.IntegerField()),
                ('jourSemaine', models.CharField(max_length=50)),
                ('isWeekEnd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('idTypeVehicule', models.AutoField(primary_key=True, serialize=False)),
                ('nomTypeVehicule', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feu',
            fields=[
                ('idFeu', models.AutoField(primary_key=True, serialize=False)),
                ('nomFeu', models.CharField(max_length=50)),
                ('etatFeu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.etatfeu')),
                ('rue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feux', to='app.rue')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('idDetection', models.AutoField(primary_key=True, serialize=False)),
                ('rue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rue')),
                ('temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temps')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('idVehicule', models.AutoField(primary_key=True, serialize=False)),
                ('nomVehicule', models.CharField(max_length=50)),
                ('typeVehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='app.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.detection')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicule')),
            ],
        ),
    ]
