# Generated by Django 5.0 on 2024-01-02 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feu',
            name='etatFeu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etatfeu'),
        ),
    ]
